"""Fix database state

Revision ID: 28d2df112b21
Revises: ccd31b47e522
Create Date: 2025-03-20 15:37:44.521519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d2df112b21'
down_revision: Union[str, None] = 'ccd31b47e522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('analysis_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('interest_week', sa.Float(), nullable=False),
    sa.Column('additional_deposit', sa.Float(), nullable=True),
    sa.Column('deposit_frequency', sa.Integer(), nullable=True),
    sa.Column('regular_withdrawal', sa.Float(), nullable=True),
    sa.Column('withdrawal_frequency', sa.Integer(), nullable=True),
    sa.Column('projection_period', sa.Integer(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_parameters_id'), 'analysis_parameters', ['id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('beginning_balance', sa.Float(), nullable=False),
    sa.Column('additional_deposit', sa.Float(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('withdrawal', sa.Float(), nullable=True),
    sa.Column('tax_deduction', sa.Float(), nullable=True),
    sa.Column('ending_balance', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_parameters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_analysis_parameters_id'), table_name='analysis_parameters')
    op.drop_table('analysis_parameters')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
